COPR_PROJECT := suricata-stable
NAME :=		suricata-rust
SPEC :=		suricata.spec
DISTS :=	epel-7-x86_64 \
		fedora-24-x86_64 \
		fedora-25-x86_64 \
		fedora-26-x86_64 \
		fedora-rawhide-x86_64

include ../common.mk
