COPR_PROJECT :=	suricata-daily
NAME :=		suricata
DISTS :=	epel-7-x86_64 \
		fedora-28-x86_64 \
		fedora-27-x86_64 \
		fedora-26-x86_64
SPEC =		suricata-daily.spec

include daily.mk
include ../common.mk

clean::
	rm -rf RPMS
